import React, { useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { BrowserRouter, Link, Navigate, Route, Routes, useNavigate, useParams } from 'react-router-dom'
import { QueryClient, QueryClientProvider, useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { App as AntApp, Button, Card, Collapse, ConfigProvider, Descriptions, Drawer, Form, Input, InputNumber, Layout, Menu, message, Popconfirm, Select, Space, Spin, Statistic, Table, Tag, Tree, Typography } from 'antd'
import { ApiOutlined, FolderOpenOutlined, PlayCircleOutlined, PlusOutlined, RobotOutlined, UnorderedListOutlined } from '@ant-design/icons'
import { api, type Agent, type AgentRun, type CreateAgentInput, type WorkspaceEntry } from './api'
import 'antd/dist/reset.css'
import './styles.css'

const { Header, Sider, Content } = Layout
const client = new QueryClient()
const statusColor: Record<string, string> = { running: 'green', stopped: 'default', provisioning: 'blue', failed: 'red', completed: 'green' }
function Shell() { return <Layout className="app"><Sider width={232} theme="light" className="sider"><div className="brand"><RobotOutlined /> AgentForge</div><Menu mode="inline" selectedKeys={[location.pathname.startsWith('/runs') ? 'runs' : 'agents']} items={[{ key: 'agents', icon: <RobotOutlined />, label: <Link to="/agents">Agents</Link> }, { key: 'runs', icon: <UnorderedListOutlined />, label: <Link to="/runs">Runs</Link> }]} /></Sider><Layout><Header className="header"><Space><ApiOutlined /> Control Plane <Tag color="green">Healthy</Tag></Space><Typography.Text type="secondary">local-dev</Typography.Text></Header><Content className="content"><Routes><Route path="/agents" element={<AgentsPage />} /><Route path="/agents/:id" element={<AgentDetail />} /><Route path="/runs" element={<RunsPage />} /><Route path="*" element={<Navigate to="/agents" replace />} /></Routes></Content></Layout></Layout> }
function AgentsPage() { const nav=useNavigate(); const [open,setOpen]=useState(false); const q=useQuery({queryKey:['agents'],queryFn:api.agents,refetchInterval:5000}); const columns=[{title:'Name',dataIndex:'name',render:(v:string,r:Agent)=><Link to={`/agents/${r.id}`}>{v}</Link>},{title:'Role',dataIndex:'role'},{title:'Model',dataIndex:'model'},{title:'Status',dataIndex:'status',render:(v:string)=><Tag color={statusColor[v]}>{v}</Tag>},{title:'Container',dataIndex:'containerId',render:(v:string)=><Typography.Text code>{v ? v.slice(0,12) : '—'}</Typography.Text>},{title:'Updated',dataIndex:'updatedAt',render:(v:string)=>new Date(v).toLocaleString()}]; return <><div className="page-head"><div><Typography.Title level={2}>Agents</Typography.Title><Typography.Text type="secondary">Create and operate isolated persistent Agents.</Typography.Text></div><Button type="primary" icon={<PlusOutlined />} onClick={()=>setOpen(true)}>Create Agent</Button></div><Card><Table rowKey="id" loading={q.isLoading} columns={columns} dataSource={q.data} pagination={false} locale={{emptyText:'No Agents yet'}} onRow={(r)=>({onDoubleClick:()=>nav(`/agents/${r.id}`)})}/></Card><CreateDrawer open={open} close={()=>setOpen(false)} /></> }
function CreateDrawer({open,close}:{open:boolean;close:()=>void}) { const [form]=Form.useForm<CreateAgentInput>();const nav=useNavigate();const qc=useQueryClient();const m=useMutation({mutationFn:api.createAgent,onSuccess:a=>{message.success('Agent created');qc.invalidateQueries({queryKey:['agents']});close();nav(`/agents/${a.id}`)},onError:(e:Error)=>message.error(e.message)});return <Drawer title="Create Agent" open={open} width={560} onClose={close} extra={<Button type="primary" loading={m.isPending} onClick={()=>form.submit()}>Create</Button>}><Form form={form} layout="vertical" initialValues={{model:'glm-4.7-flash',workspacePolicy:'retain',tools:['bash','fs_read','fs_write'],cpuQuotaUs:50000,memoryMb:256,pidsLimit:256}} onFinish={v=>m.mutate(v)}><Form.Item label="Name" name="name" rules={[{required:true,min:2}]}><Input placeholder="research-agent" /></Form.Item><Form.Item label="Role" name="role" rules={[{required:true}]}><Input placeholder="Research assistant" /></Form.Item><Form.Item label="System prompt" name="systemPrompt"><Input.TextArea rows={5} placeholder="You are a careful research assistant…" /></Form.Item><Form.Item label="Model" name="model"><Input disabled /></Form.Item><Collapse items={[{key:'advanced',label:'Advanced configuration',children:<><Form.Item label="Container image" name="image"><Input placeholder="alpine:3.19" /></Form.Item><Space size="large"><Form.Item label="CPU quota (µs)" name="cpuQuotaUs"><InputNumber min={1000}/></Form.Item><Form.Item label="Memory (MB)" name="memoryMb"><InputNumber min={64}/></Form.Item><Form.Item label="PID limit" name="pidsLimit"><InputNumber min={16}/></Form.Item></Space><Form.Item label="Tools" name="tools"><Select mode="multiple" options={['bash','fs_read','fs_write','fs_list','http_fetch'].map(value=>({value}))}/></Form.Item><Form.Item label="Workspace on deletion" name="workspacePolicy"><Select options={[{value:'retain',label:'Retain workspace'},{value:'delete',label:'Delete workspace'}]}/></Form.Item></>}]}/></Form></Drawer> }
function AgentDetail(){const {id=''}=useParams();const qc=useQueryClient();const q=useQuery({queryKey:['agent',id],queryFn:()=>api.agent(id),refetchInterval:5000});const m=useMutation({mutationFn:(action:'start'|'stop'|'delete')=>api.agentAction(id,action),onSuccess:(_,action)=>{if(action==='delete'){location.href='/agents'}else{qc.invalidateQueries({queryKey:['agent',id]})}},onError:(e:Error)=>message.error(e.message)});if(q.isLoading)return <Spin/>;if(!q.data)return null;return <><div className="page-head"><div><Typography.Title level={2}>{q.data.name}</Typography.Title><Tag color={statusColor[q.data.status]}>{q.data.status}</Tag> <Typography.Text type="secondary">{q.data.role}</Typography.Text></div><Space>{q.data.status==='running'?<Button onClick={()=>m.mutate('stop')}>Stop</Button>:<Button type="primary" onClick={()=>m.mutate('start')}>Start</Button>}<Popconfirm title="Delete this Agent?" onConfirm={()=>m.mutate('delete')}><Button danger>Delete</Button></Popconfirm></Space></div><div className="workspace-grid"><AgentOverview agent={q.data}/><RunPanel agent={q.data}/><Workspace agent={q.data}/></div></>}
function AgentOverview({agent}:{agent:Agent}){return <Card title="Agent overview"><Descriptions column={1} size="small"><Descriptions.Item label="Model">{agent.model}</Descriptions.Item><Descriptions.Item label="Image">{agent.image}</Descriptions.Item><Descriptions.Item label="CPU">{agent.cpuQuotaUs} µs</Descriptions.Item><Descriptions.Item label="Memory">{agent.memoryMb} MB</Descriptions.Item><Descriptions.Item label="Volume">{agent.volumeName}</Descriptions.Item></Descriptions></Card>}
type RunEvent={id:number;type:string;data:Record<string,unknown>};function RunPanel({agent}:{agent:Agent}){const qc=useQueryClient();const [prompt,setPrompt]=useState('');const [events,setEvents]=useState<RunEvent[]>([]);const [active,setActive]=useState<string>();const runs=useQuery({queryKey:['runs',agent.id],queryFn:()=>api.runs(agent.id)});const m=useMutation({mutationFn:()=>api.startRun(agent.id,prompt),onSuccess:r=>{setEvents([]);setActive(r.runId);setPrompt('');qc.invalidateQueries({queryKey:['runs',agent.id]})},onError:(e:Error)=>message.error(e.message)});useEffect(()=>{if(!active)return;let closed=false;const source=new EventSource(`/api/v1/runs/${active}/events`);for(const type of ['state','token','done','error'])source.addEventListener(type,(raw)=>{const e=raw as MessageEvent;setEvents(v=>[...v,{id:Number(e.lastEventId),type,data:JSON.parse(e.data)}]);if(type==='done'||type==='error'){source.close();setActive(undefined);qc.invalidateQueries({queryKey:['runs',agent.id]})}});source.onerror=()=>{if(!closed)source.close()};return()=>{closed=true;source.close()}},[active,agent.id,qc]);const text=useMemo(()=>events.filter(e=>e.type==='token').map(e=>String(e.data.text??'')).join(''),[events]);return <Card title="Run task" className="run-card"><Input.TextArea value={prompt} onChange={e=>setPrompt(e.target.value)} rows={4} placeholder="Ask this Agent to work…" disabled={agent.status!=='running'||m.isPending||!!active}/><Button type="primary" icon={<PlayCircleOutlined/>} className="run-button" loading={m.isPending} disabled={!prompt.trim()||agent.status!=='running'||!!active} onClick={()=>m.mutate()}>Run</Button><div className="run-output">{events.filter(e=>e.type==='state').map(e=><Tag key={e.id}>{String(e.data.to)}</Tag>)}{text||(!active&&'Output will stream here.')}{events.find(e=>e.type==='error')&&<Typography.Text type="danger">{String(events.find(e=>e.type==='error')?.data.message)}</Typography.Text>}</div><Typography.Title level={5}>Recent runs</Typography.Title>{runs.data?.slice(0,4).map(r=><div className="run-row" key={r.runId}><Tag color={statusColor[r.status]}>{r.status}</Tag><Typography.Text ellipsis>{r.prompt}</Typography.Text></div>)}</Card>}
function Workspace({agent}:{agent:Agent}){const [folder,setFolder]=useState('');const [file,setFile]=useState('');const entries=useQuery({queryKey:['workspace',agent.id,folder],queryFn:()=>api.workspace(agent.id,folder),enabled:agent.status==='running'});const content=useQuery({queryKey:['workspace-file',agent.id,file],queryFn:()=>api.workspaceFile(agent.id,file),enabled:!!file});const nodes=(entries.data??[]).map((x:WorkspaceEntry)=>({key:x.path,title:<span onClick={()=>x.directory?setFolder(x.path):setFile(x.path)}>{x.directory?<FolderOpenOutlined/>:null} {x.name}</span>,isLeaf:!x.directory}));return <Card title="Workspace" className="workspace-card"><Typography.Text type="secondary">Read-only persistent volume</Typography.Text><Tree treeData={nodes} /><Typography.Paragraph code className="file-content">{content.data?.content||'Select a text file to preview.'}</Typography.Paragraph></Card>}
function RunsPage(){const q=useQuery({queryKey:['runs'],queryFn:()=>api.runs()});return <><div className="page-head"><div><Typography.Title level={2}>Runs</Typography.Title><Typography.Text type="secondary">Recent execution history across all Agents.</Typography.Text></div></div><Card><Table rowKey="runId" loading={q.isLoading} dataSource={q.data} pagination={{pageSize:20}} columns={[{title:'Run',dataIndex:'runId',render:(v:string)=><Typography.Text code>{v.slice(-10)}</Typography.Text>},{title:'Agent',dataIndex:'agentId',render:(v:string)=><Link to={`/agents/${v}`}>{v.slice(-10)}</Link>},{title:'Status',dataIndex:'status',render:(v:string)=><Tag color={statusColor[v]}>{v}</Tag>},{title:'Prompt',dataIndex:'prompt'},{title:'Created',dataIndex:'createdAt',render:(v:string)=>new Date(v).toLocaleString()}]}/></Card></>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><BrowserRouter><ConfigProvider theme={{token:{colorPrimary:'#1677ff',borderRadius:6}}}><QueryClientProvider client={client}><AntApp><Shell/></AntApp></QueryClientProvider></ConfigProvider></BrowserRouter></React.StrictMode>)
