import React, { useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { BrowserRouter, Link, Navigate, Route, Routes, useLocation, useNavigate, useParams } from 'react-router-dom'
import { QueryClient, QueryClientProvider, useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Alert, App as AntApp, Button, Card, Collapse, ConfigProvider, Descriptions, Drawer, Form, Input, InputNumber, Layout, Menu, message, Popconfirm, Select, Space, Spin, Steps, Table, Tag, Tree, Typography } from 'antd'
import { ApiOutlined, ArrowLeftOutlined, BookOutlined, CloudServerOutlined, DatabaseOutlined, FileSearchOutlined, FolderOpenOutlined, HistoryOutlined, HomeOutlined, PlayCircleOutlined, PlusOutlined, RobotOutlined, SafetyCertificateOutlined, SettingOutlined, ThunderboltOutlined, UnorderedListOutlined } from '@ant-design/icons'
import { api, type Agent, type AgentRun, type CreateAgentInput, type WorkspaceEntry } from './api'
import { AGENT_MODEL_OPTIONS, DEFAULT_AGENT_MODEL } from './models'
import 'antd/dist/reset.css'
import './styles.css'

const { Header, Sider, Content } = Layout
const client = new QueryClient()
const statusColor: Record<string, string> = { running: 'green', stopped: 'default', provisioning: 'blue', failed: 'red', completed: 'green' }
const motionStatus = (status:string) => `status-tag status-${status}`
function StatusTag({status}:{status:string}){return <Tag color={statusColor[status]} className={motionStatus(status)}>{status}</Tag>}
function Shell() { const { pathname }=useLocation(); const selected=pathname.startsWith('/runs')?'runs':pathname.startsWith('/guide')?'guide':'agents'; return <Layout className="app"><Sider width={252} theme="dark" className="sider"><div className="brand"><span className="brand-mark"><RobotOutlined /></span><span>AgentForge<small>RUNTIME CONSOLE</small></span></div><Menu mode="inline" theme="dark" selectedKeys={[selected]} items={[{ key: 'agents', icon: <RobotOutlined />, label: <Link to="/agents">Agents</Link> }, { key: 'runs', icon: <UnorderedListOutlined />, label: <Link to="/runs">Runs</Link> }, { key: 'guide', icon: <BookOutlined />, label: <Link to="/guide">使用指南</Link> }]} /><div className="sider-footer"><span className="health-dot"/>Control Plane connected</div></Sider><Layout><Header className="header"><div className="header-context"><ApiOutlined /><span>CONTROL PLANE</span><i>·</i><span className="header-route">{selected}</span></div><Space size="middle"><Tag color="success" className="health-tag"><span className="health-dot"/>Healthy</Tag><Typography.Text className="environment-label">local-dev</Typography.Text></Space></Header><Content className="content"><div className="route-motion" key={pathname}><Routes><Route path="/agents" element={<AgentsPage />} /><Route path="/agents/:id" element={<AgentDetail />} /><Route path="/runs" element={<RunsPage />} /><Route path="/guide" element={<GuidePage />} /><Route path="*" element={<Navigate to="/agents" replace />} /></Routes></div></Content></Layout></Layout> }
const guideCapabilities = [
  { icon:<RobotOutlined/>, title:'创建持久 Agent', text:'为每个 Agent 设置名称、角色、系统提示词，并选择智谱 GLM-4.7-Flash 或 ModelScope Qwen3.5-35B-A3B。每个 Agent 拥有独立 Docker 容器和持久工作区。' },
  { icon:<SettingOutlined/>, title:'配置运行策略', text:'在高级配置中设置容器镜像、CPU、内存、PID 上限、工具 allow-list，以及删除 Agent 时是否保留工作区。' },
  { icon:<CloudServerOutlined/>, title:'管理生命周期', text:'在详情页启动、停止或删除 Agent，并查看容器、模型、资源配额和 workspace volume 等运行信息。' },
  { icon:<ThunderboltOutlined/>, title:'实时执行任务', text:'直接向运行中的 Agent 提交任务，查看状态变化、流式 token、错误或完成结果。同一 Agent 同时只执行一个活跃任务。' },
  { icon:<FileSearchOutlined/>, title:'浏览只读工作区', text:'查看 Agent 持久工作区中的目录和文本文件。Dashboard 仅提供安全的只读预览，不在线修改或删除文件。' },
  { icon:<HistoryOutlined/>, title:'追踪运行历史', text:'在 Agent 详情中查看最近运行，也可以在 Runs 页面查看所有 Agent 的全局执行记录和状态。' },
]
function GuidePage(){return <div className="guide-page"><Card className="guide-hero"><div className="guide-hero-content"><div><Tag color="blue">Developer Console</Tag><Typography.Title level={1}>用一个 Dashboard 管理你的 AI Agents</Typography.Title><Typography.Paragraph>AgentForge 将 Agent 的创建、隔离运行、任务执行和工作区查看集中到浏览器中。无需从前端直接接触 Docker、Redis、gRPC 或内部服务。</Typography.Paragraph><Space wrap><Link to="/agents"><Button type="primary" icon={<PlusOutlined/>}>创建第一个 Agent</Button></Link><Link to="/runs"><Button icon={<HistoryOutlined/>}>查看运行记录</Button></Link></Space></div><div className="guide-hero-mark"><RobotOutlined/><span>Agent Control Plane</span></div></div></Card><div className="guide-section"><div className="guide-section-head"><Typography.Title level={3}>你可以做什么</Typography.Title><Typography.Text type="secondary">从 Agent 配置到运行结果，完成一条可观察的本地开发闭环。</Typography.Text></div><div className="guide-capability-grid">{guideCapabilities.map(item=><Card key={item.title} className="guide-capability"><div className="guide-capability-icon">{item.icon}</div><Typography.Title level={4}>{item.title}</Typography.Title><Typography.Paragraph type="secondary">{item.text}</Typography.Paragraph></Card>)}</div></div><Card title="推荐操作流程" className="guide-flow"><Steps responsive items={[{title:'创建 Agent',description:'填写角色、提示词和资源策略'},{title:'等待 Running',description:'Control Plane 创建容器与工作区'},{title:'提交任务',description:'在详情页查看流式执行过程'},{title:'检查结果',description:'查看输出、历史和只读文件'},{title:'停止或保留',description:'按需停止 Agent，工作区继续持久化'}]}/></Card><div className="guide-notes"><Alert type="info" showIcon icon={<SafetyCertificateOutlined/>} message="当前版本的运行规则" description="Dashboard 面向本地或受信任开发环境，使用 local-dev 身份。每个 Agent 同时仅允许一个活跃 run，以避免共享工作区写冲突。"/><Alert type="warning" showIcon icon={<DatabaseOutlined/>} message="首版暂未提供" description="多 Agent 拓扑与 ACP 协作编排、RAG 文档管理、工作区在线编辑、登录、多租户和 RBAC 将在后续版本开放。"/></div></div>}
function AgentsPage() { const nav=useNavigate(); const [open,setOpen]=useState(false); const q=useQuery({queryKey:['agents'],queryFn:api.agents,refetchInterval:5000}); const columns=[{title:'Name',dataIndex:'name',render:(v:string,r:Agent)=><Link to={`/agents/${r.id}`}>{v}</Link>},{title:'Role',dataIndex:'role'},{title:'Model',dataIndex:'model'},{title:'Status',dataIndex:'status',render:(v:string)=><StatusTag status={v}/>},{title:'Container',dataIndex:'containerId',render:(v:string)=><Typography.Text code>{v ? v.slice(0,12) : '—'}</Typography.Text>},{title:'Updated',dataIndex:'updatedAt',render:(v:string)=>new Date(v).toLocaleString()}]; return <div className="agents-page"><div className="page-head"><div><span className="eyebrow">AGENT REGISTRY</span><Typography.Title level={2}>Agents</Typography.Title><Typography.Text type="secondary">Create and operate isolated, persistent Agents.</Typography.Text></div><Button type="primary" icon={<PlusOutlined />} onClick={()=>setOpen(true)}>Create Agent</Button></div><Card className="console-table" title={<span className="card-title">Active registry <small>{q.data?.length ?? 0} configured</small></span>}><Table rowKey="id" loading={q.isLoading} columns={columns} dataSource={q.data} pagination={false} locale={{emptyText:'No Agents yet'}} onRow={(r)=>({onDoubleClick:()=>nav(`/agents/${r.id}`)})}/></Card><CreateDrawer open={open} close={()=>setOpen(false)} /></div> }
function CreateDrawer({open,close}:{open:boolean;close:()=>void}) { const [form]=Form.useForm<CreateAgentInput>();const nav=useNavigate();const qc=useQueryClient();const m=useMutation({mutationFn:api.createAgent,onSuccess:a=>{message.success('Agent created');qc.invalidateQueries({queryKey:['agents']});close();nav(`/agents/${a.id}`)},onError:(e:Error)=>message.error(e.message)});return <Drawer title="Create Agent" open={open} width={560} onClose={close} extra={<Button type="primary" loading={m.isPending} onClick={()=>form.submit()}>Create</Button>}><Form form={form} layout="vertical" initialValues={{model:DEFAULT_AGENT_MODEL,workspacePolicy:'retain',tools:['bash','fs_read','fs_write'],cpuQuotaUs:50000,memoryMb:256,pidsLimit:256}} onFinish={v=>m.mutate(v)}><Form.Item label="Name" name="name" rules={[{required:true,min:2}]}><Input placeholder="research-agent" /></Form.Item><Form.Item label="Role" name="role" rules={[{required:true}]}><Input placeholder="Research assistant" /></Form.Item><Form.Item label="System prompt" name="systemPrompt"><Input.TextArea rows={5} placeholder="You are a careful research assistant…" /></Form.Item><Form.Item label="Model" name="model"><Select options={AGENT_MODEL_OPTIONS} /></Form.Item><Collapse items={[{key:'advanced',label:'Advanced configuration',children:<><Form.Item label="Container image" name="image"><Input placeholder="alpine:3.19" /></Form.Item><Space size="large"><Form.Item label="CPU quota (µs)" name="cpuQuotaUs"><InputNumber min={1000}/></Form.Item><Form.Item label="Memory (MB)" name="memoryMb"><InputNumber min={64}/></Form.Item><Form.Item label="PID limit" name="pidsLimit"><InputNumber min={16}/></Form.Item></Space><Form.Item label="Tools" name="tools"><Select mode="multiple" options={['bash','fs_read','fs_write','fs_list','http_fetch'].map(value=>({value}))}/></Form.Item><Form.Item label="Workspace on deletion" name="workspacePolicy"><Select options={[{value:'retain',label:'Retain workspace'},{value:'delete',label:'Delete workspace'}]}/></Form.Item></>}]}/></Form></Drawer> }
function AgentDetail(){const {id=''}=useParams();const qc=useQueryClient();const q=useQuery({queryKey:['agent',id],queryFn:()=>api.agent(id),refetchInterval:5000});const m=useMutation({mutationFn:(action:'start'|'stop'|'delete')=>api.agentAction(id,action),onSuccess:(_,action)=>{if(action==='delete'){location.href='/agents'}else{qc.invalidateQueries({queryKey:['agent',id]})}},onError:(e:Error)=>message.error(e.message)});if(q.isLoading)return <Spin/>;if(!q.data)return null;return <><div className="page-head"><div><Typography.Title level={2}>{q.data.name}</Typography.Title><StatusTag status={q.data.status}/> <Typography.Text type="secondary">{q.data.role}</Typography.Text></div><Space>{q.data.status==='running'?<Button onClick={()=>m.mutate('stop')}>Stop</Button>:<Button type="primary" onClick={()=>m.mutate('start')}>Start</Button>}<Popconfirm title="Delete this Agent?" onConfirm={()=>m.mutate('delete')}><Button danger>Delete</Button></Popconfirm></Space></div><div className="workspace-grid"><AgentOverview agent={q.data}/><RunPanel agent={q.data}/><Workspace agent={q.data}/></div></>}
function AgentOverview({agent}:{agent:Agent}){return <Card title="Agent overview"><Descriptions column={1} size="small"><Descriptions.Item label="Model">{agent.model}</Descriptions.Item><Descriptions.Item label="Image">{agent.image}</Descriptions.Item><Descriptions.Item label="CPU">{agent.cpuQuotaUs} µs</Descriptions.Item><Descriptions.Item label="Memory">{agent.memoryMb} MB</Descriptions.Item><Descriptions.Item label="Volume">{agent.volumeName}</Descriptions.Item></Descriptions></Card>}
type RunEvent={id:number;type:string;data:Record<string,unknown>};function RunPanel({agent}:{agent:Agent}){const qc=useQueryClient();const [prompt,setPrompt]=useState('');const [events,setEvents]=useState<RunEvent[]>([]);const [active,setActive]=useState<string>();const runs=useQuery({queryKey:['runs',agent.id],queryFn:()=>api.runs(agent.id)});const m=useMutation({mutationFn:()=>api.startRun(agent.id,prompt),onSuccess:r=>{setEvents([]);setActive(r.runId);setPrompt('');qc.invalidateQueries({queryKey:['runs',agent.id]})},onError:(e:Error)=>message.error(e.message)});useEffect(()=>{if(!active)return;let closed=false;const source=new EventSource(`/api/v1/runs/${active}/events`);for(const type of ['state','token','done','error'])source.addEventListener(type,(raw)=>{const e=raw as MessageEvent;setEvents(v=>[...v,{id:Number(e.lastEventId),type,data:JSON.parse(e.data)}]);if(type==='done'||type==='error'){source.close();setActive(undefined);qc.invalidateQueries({queryKey:['runs',agent.id]});qc.invalidateQueries({queryKey:['workspace',agent.id]})}});source.onerror=()=>{if(!closed)source.close()};return()=>{closed=true;source.close()}},[active,agent.id,qc]);const text=useMemo(()=>events.filter(e=>e.type==='token').map(e=>String(e.data.text??'')).join(''),[events]);return <Card title="Run task" className="run-card"><Input.TextArea value={prompt} onChange={e=>setPrompt(e.target.value)} rows={4} placeholder="Ask this Agent to work…" disabled={agent.status!=='running'||m.isPending||!!active}/><Button type="primary" icon={<PlayCircleOutlined/>} className="run-button" loading={m.isPending} disabled={!prompt.trim()||agent.status!=='running'||!!active} onClick={()=>m.mutate()}>Run</Button><div className={`run-output${active?' is-active':''}`} aria-live="polite">{events.filter(e=>e.type==='state').map(e=><Tag key={e.id} className="event-enter">{String(e.data.to)}</Tag>)}{text||(!active&&'Output will stream here.')}{events.find(e=>e.type==='error')&&<Typography.Text type="danger" className="event-enter">{String(events.find(e=>e.type==='error')?.data.message)}</Typography.Text>}</div><Typography.Title level={5}>Recent runs</Typography.Title>{runs.data?.slice(0,4).map(r=><div className="run-row" key={r.runId}><StatusTag status={r.status}/><Typography.Text ellipsis>{r.prompt}</Typography.Text></div>)}</Card>}
function Workspace({agent}:{agent:Agent}){const [folder,setFolder]=useState('');const [file,setFile]=useState('');const entries=useQuery({queryKey:['workspace',agent.id,folder],queryFn:()=>api.workspace(agent.id,folder),enabled:agent.status==='running'});const content=useQuery({queryKey:['workspace-file',agent.id,file],queryFn:()=>api.workspaceFile(agent.id,file),enabled:!!file});const openFolder=(path:string)=>{setFolder(path);setFile('')};const parent=folder.split('/').slice(0,-1).join('/');const nodes=(entries.data??[]).map((x:WorkspaceEntry)=>({key:x.path,title:<span onClick={()=>x.directory?openFolder(x.path):setFile(x.path)}>{x.directory?<FolderOpenOutlined/>:null} {x.name}</span>,isLeaf:!x.directory}));return <Card title="Workspace" className="workspace-card"><Typography.Text type="secondary">Read-only persistent volume</Typography.Text><div className="workspace-toolbar"><Space size="small"><Button size="small" icon={<ArrowLeftOutlined/>} disabled={!folder} onClick={()=>openFolder(parent)}>上一级</Button><Button size="small" icon={<HomeOutlined/>} disabled={!folder} onClick={()=>openFolder('')}>根目录</Button></Space><Typography.Text key={folder||'/'} code ellipsis title={`/${folder}`} className="workspace-path-motion">/{folder}</Typography.Text></div><div key={folder||'/'} className="workspace-tree-motion">{entries.isLoading?<Spin size="small"/>:<Tree treeData={nodes}/>}</div><Typography.Paragraph key={file||'empty'} code className="file-content file-preview-motion">{content.data?.content||'Select a text file to preview.'}</Typography.Paragraph></Card>}
function RunsPage(){const q=useQuery({queryKey:['runs'],queryFn:()=>api.runs()});return <div className="runs-page"><div className="page-head"><div><span className="eyebrow">EXECUTION LEDGER</span><Typography.Title level={2}>Runs</Typography.Title><Typography.Text type="secondary">Recent execution history across all Agents.</Typography.Text></div></div><Card className="console-table" title={<span className="card-title">Run history <small>latest activity</small></span>}><Table rowKey="runId" loading={q.isLoading} dataSource={q.data} pagination={{pageSize:20}} columns={[{title:'Run',dataIndex:'runId',render:(v:string)=><Typography.Text code>{v.slice(-10)}</Typography.Text>},{title:'Agent',dataIndex:'agentId',render:(v:string)=><Link to={`/agents/${v}`}>{v.slice(-10)}</Link>},{title:'Status',dataIndex:'status',render:(v:string)=><StatusTag status={v}/>},{title:'Prompt',dataIndex:'prompt'},{title:'Created',dataIndex:'createdAt',render:(v:string)=>new Date(v).toLocaleString()}]}/></Card></div>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><BrowserRouter><ConfigProvider theme={{token:{colorPrimary:'#0b9a9c',colorInfo:'#2776d2',colorSuccess:'#36aa72',colorText:'#172337',colorTextSecondary:'#68758a',colorBgLayout:'#edf2f5',colorBorderSecondary:'#dce4ea',borderRadius:10,fontFamily:'Avenir Next, Avenir, PingFang SC, Microsoft YaHei, sans-serif'},components:{Menu:{darkItemBg:'#102033',darkSubMenuItemBg:'#102033',darkItemSelectedBg:'#163c50',darkItemHoverBg:'#173147'},Card:{headerBg:'transparent'}}}}><QueryClientProvider client={client}><AntApp><Shell/></AntApp></QueryClientProvider></ConfigProvider></BrowserRouter></React.StrictMode>)
